PBK = RegisterMod("PBK", 1)

-- Require other Lua files and capture the returned item ID

require("items.allfather_worm")
require("items.stale_burrito")
require("items.ash_crown")
require("items.battery_booster")
require("items.bee_buster")
require("items.bewitching_howl")
require("items.chirping_alarm")
require("items.covenant_of_ashes")
require("items.crickets_bed")
require("items.damage_potion")
require("items.dammys_dilemma")
require("items.duality_mirror")
require("items.heartburn")
require("items.hollow_echo")
require("items.loaded_die")
require("items.optic_bomb")
require("items.paper_shredder")
require("items.pollen")
require("items.pseudotheism")
require("items.purgatory_flame")
require("items.pyro_mantle")
require("items.rock_buster")
require("items.rule_of_power")
require("items.smouldering_dice")
require("items.the_button")
require("items.volcanic_sigil")
require("items.popcorn_kernel")
require("items.borrowed_time")
require("items.bell_pepper")

require("character.king_manasse")
require("character.null")
--- require("character.t_king_manasse")
require("trinkets.fragment_of_sol")
